version: '3.9'

services:
  mysql:
    image: mysql:8.4
    container_name: shieldx-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 2300033901
      MYSQL_DATABASE: sheidx
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./ShieldX-Backend/SheidX
    container_name: shieldx-backend
    restart: unless-stopped
    environment:
      DB_URL: jdbc:mysql://mysql:3306/sheidx?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASSWORD: 2300033901
      JWT_ACCESS_SECRET: shieldx-access-secret-key-must-be-very-long-2026
      JWT_REFRESH_SECRET: shieldx-refresh-secret-key-must-be-very-long-2026
    depends_on:
      - mysql
    ports:
      - "9999:9999"

  frontend:
    build:
      context: ./ShieldX-Frontend/ShieldX
    container_name: shieldx-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mysql_data:
