apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shieldx-ingress
spec:
  rules:
    - host: shieldx.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shieldx-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: shieldx-backend
                port:
                  number: 9999
