package com.sheildX.proj.service;

import java.util.List;

import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import com.sheildX.proj.dto.AutomatedTriggerSignalDTO;

@Service
public class TriggerAutomationService {

    private final UserService userService;
    private final MockDisruptionFeedService mockDisruptionFeedService;
    private final TriggerService triggerService;

    public TriggerAutomationService(
        UserService userService,
        MockDisruptionFeedService mockDisruptionFeedService,
        TriggerService triggerService
    ) {
        this.userService = userService;
        this.mockDisruptionFeedService = mockDisruptionFeedService;
        this.triggerService = triggerService;
    }

    @Scheduled(fixedDelayString = "${shieldx.triggers.auto-generate-ms:45000}")
    public void autoGenerateDisruptionTriggers() {
        List<String> zones = userService.getAllUsers().stream().map(user -> user.getZone().trim()).distinct().toList();
        if (zones.isEmpty()) {
            return;
        }

        List<AutomatedTriggerSignalDTO> signals = mockDisruptionFeedService.generateSignalsForZones(zones);
        for (AutomatedTriggerSignalDTO signal : signals) {
            triggerService.createAutomatedTrigger(signal);
        }
    }
}
